### ISSUE TITLE
golypus checklist

### ISSUE THREAD

**Issue by FelipeMCassiano** [FelipeMCassiano/golypus#1]
Container Management

 - [ ] Start containers
 - [ ] Stop containers
 - [ ] Restart containers
 - [ ] Resource Management

  - [ ] Set CPU limits
  - [ ] Set memory limits
  - [ ] Manage disk I/O
  - [ ] Implement dynamic scaling based on load/metrics
 - [ ] Container Monitoring

  - [ ] Implement health checks for containers
  - [ ] Automatically restart unhealthy containers
 - [ ]  Collect and store logs
 - [ ]  Gather and store metrics (CPU, memory, etc.)
 
 ## Networking
  - [ ] Manage container networks
  - [ ] Setup inter-container communication
  - [ ] Implement service discovery
 
## Security
  - [ ] Ensure container isolation
  - [ ]S et up user namespaces and permissions
  - [ ] Restrict capabilities of containers
  - [ ] Manage secure pulling and usage of Docker images
   
  ## Scalability and High Availability

  - [ ] Implement cluster management (e.g., Docker Swarm/Kubernetes)
  - [ ] Ensure high availability of containers
  - [ ] Implement auto-healing for failed containers
 
## Extensibility
  - [ ] Allow custom workflows (e.g., pre/post container start/stop commands)
  - [ ] Provide APIs for integration with CI/CD systems
  - [ ] Integrate with monitoring and logging tools
  
##Efficiency
 Optimize performance and resource usage of the controller
 Handle concurrent container operations efficiently
